### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by audiolion** [jazzband/django-auditlog#122]
Add a `CHANGELOG` to easily track updates, especially since in the <1.0.0 versions we likely have breaking changes on each release.

**Comment by Linkid** [comment]
Done in https://github.com/jazzband/django-auditlog/commit/ca5aa82714f9f111e3cc82fb9fa08cf04d67bf8a#diff-ff3c479edefad986d2fe6fe7ead575a46b086e3bbcf0ccc86d85efc4a4c63c79.
