### ISSUE TITLE
one to one relation error

### ISSUE THREAD

**Issue by ghost** [jazzband/django-auditlog#169]
one to one relation error happening on diff.py line 80 where field object does not have attribute default if onetoonerel type field. suggested patch
            if hasattr(field, 'default'):
                value = field.default if field.default is not NOT_PROVIDED else None
            else:
                value = None

**Comment by audiolion** [comment]
hey, can you provide a stack trace or test case that shows the error?

**Comment by stherrien** [comment]
Same error also suggesting one line patch
value = field.default if getattr(field, 'default', NOT_PROVIDED) is not NOT_PROVIDED else None

stack trace:
File "pkgs/auditlog/diff.py", line 135, in model_instance_diff
    new_value = get_field_value(new, field)
  File "pkgs/auditlog/diff.py", line 80, in get_field_value
    value = field.default if field.default is not NOT_PROVIDED else None
AttributeError: 'OneToOneRel' object has no attribute 'default'

**Comment by bynare** [comment]
I was also hitting this, when using the audit log with [django-polymorphic](https://django-polymorphic.readthedocs.io/en/stable/)

Here is a [pull request](https://github.com/jjkester/django-auditlog/pull/224) ;)

**Comment by hramezani** [comment]
Fixed in https://github.com/jazzband/django-auditlog/commit/a56d0e6f784f3d0e1107f41c8c7a3f2423686c14
