### ISSUE TITLE
0.4.7 records wrong changes when saving with update_fields parameter

### ISSUE THREAD

**Issue by one10** [jazzband/django-auditlog#243]
Have been using `django-auditlog` for some time now, mostly happy. However, found out the hard way that when I restrict Django saves to certain fields using e.g.:

`model.save(update_fields=['field1'])` 

with the `update_fields` parameter, `django-auditlog` will log non-existent changes from many fields that were not, in fact, modified in the actual model's table row at all.

Quickly grepping through `django-auditlog`'s source code, I don't see any mention of update_fields, but this parameter to save() needs to be considered, because the model data that gets saved using this restriction can result in an inaccurate auditlog entry that cannot be trusted.

**Comment by hramezani** [comment]
Fixed in https://github.com/jazzband/django-auditlog/commit/54dc20e92083cd3aafe445dbe41750157246f36b
