### ISSUE TITLE
Import issues with python_2_unicode_compatible

### ISSUE THREAD

**Issue by i-jonathan** [jazzband/django-auditlog#265]
Django = 3.1.1
django-auditlog = 0.4.7

Error Messages:

**redacted**\lib\site-packages\auditlog\registry.py", line 5, in <module>
    from django.utils.six import iteritems
ModuleNotFoundError: No module named 'django.utils.six'

Fixed by installing django-utils-six ~= 2.0
`pip install django-utils-six`

**redacted**\lib\site-packages\auditlog\models.py", line 13, in <module>
    from django.utils.encoding import python_2_unicode_compatible, smart_text
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding' (**redacted**\lib\site-packages\django\utils\encoding.py)

**and**

**replace:** 
`from django.utils.encoding import python_2_unicode_compatible`
**with:**
`from six import python_2_unicode_compatible`

**Comment by Real-Gecko** [comment]
Confirming!

**Comment by Real-Gecko** [comment]
Looks like everything is fine with latest master 565239180e2cc386156e80c98566df2c77f55463

**Comment by i-jonathan** [comment]
I still have issues with importing from django.utils.six
Django > 3.0 has removed django utils six 

https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis 

So either any import from there is removed 
Or the import is done from the 'six' package instead

**Comment by i-jonathan** [comment]
On further checking, the current branch doesn't include references to django.utils.six
Installing from pip however still brings the fault

**Comment by lijiapengsa** [comment]
use django-auditlog==1.0a1

**Comment by 1am** [comment]
For thos of you who are like me and using pipenv, installing directly from repo is as easy as `pipenv install "git+https://github.com/jazzband/django-auditlog.git@v1.0a1#egg=django-auditlog"`

**Comment by Linkid** [comment]
Seems to be done in https://github.com/jazzband/django-auditlog/commit/3acab4322b57b22d5d9874abeb8f66a774432be0.
