### ISSUE TITLE
ImportError on 'curry'

### ISSUE THREAD

**Issue by MikeSandford** [jazzband/django-auditlog#270]
I just started a new project with cookiecutter-django as of 9/26/2020 which installed django==3.0.10.  I found the #265 issue and I'm also seeing a problem importing `curry`:
```
  File "/home/sandford/work/project/venv/lib/python3.8/site-packages/auditlog/middleware.py", line 8, in <module>
    from django.utils.functional import curry
ImportError: cannot import name 'curry' from 'django.utils.functional' (/home/sandford/work/project/venv/lib/python3.8/site-packages/django/utils/functional.py)
```

I also found a solution from another project, which when pasted into the middlware.py file resolves the issue: https://github.com/saxix/django-adminactions/commit/18451a0ba07485844faf4cebba9f4a09fa3a05a2#diff-ad79f90c12c370ca9724f78e0e072d96

**Comment by Real-Gecko** [comment]
Try updating to `django-auditlog==1.0a1`

**Comment by Linkid** [comment]
Fixed in https://github.com/jazzband/django-auditlog/commit/3acab4322b57b22d5d9874abeb8f66a774432be0. Thank you :).
