### ISSUE TITLE
Remove 1.0a1 pre-release flag on pypi?

### ISSUE THREAD

**Issue by chrisittner** [jazzband/django-auditlog#291]
It's great to finally see Django 3.0/3.1 support in django-auditlog! 

I noticed that `1.0a1` is marked pre-release on pypi (https://pypi.org/project/django-auditlog/#history) so pip defaults to `0.4.7`.

Seeing that the release instructions in the readme don't mention anything about this, I was wondering if this is on purpose and   when the 3.0/.31 supporting version will become default?

**Comment by damiencarol** [comment]
any news on this one? an official release 1.0.0 ?

**Comment by valentijnscholten** [comment]
What was changed in 1.0a1? https://github.com/jazzband/django-auditlog/pull/263 is empty at the moment.

**Comment by valentijnscholten** [comment]
Looks like these are the changes (apart from later cicd related commits): https://github.com/jazzband/django-auditlog/compare/ee8a700b1b97e405638af5f9f9369651e8601583..565239180e2cc386156e80c98566df2c77f55463

**Comment by Kingjmk** [comment]
Any news on a Django 3.0 support official release?

**Comment by damiencarol** [comment]
Found this one #227

**Comment by Linkid** [comment]
Hi ! Thanks for this issue.
The alpha version is still a pre-release, so the flagged should not be removed.
A new version will be released soon. You can check #331 for more info ;).
