### ISSUE TITLE
Change using db

### ISSUE THREAD

**Issue by kairatomurbek2** [jazzband/django-auditlog#299]

**Comment by kairatomurbek2** [comment]
Let's say I have a main database, and I need the auditlog to have its own database

**Comment by kairatomurbek2** [comment]
Let's say I have a main database, and I need the auditlog to have its own database

**Comment by Linkid** [comment]
Hi ! Thanks for this issue !
This is a duplicate of #321, which has a link to the doc. So, I'm closing this issue.
