### ISSUE TITLE
Cannot import name python_2_unicode_compatible

### ISSUE THREAD

**Issue by danieljausovec** [jazzband/django-auditlog#305]
I'm using Django 3.1 and python 3.9 and when I added app in "INSTALLED_APPS" I got this error:

`ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'`

Is this related to python version or to django version or am I doing something wrong?

**Comment by 1am** [comment]
I have the same problem right now. Using Python 3.8.5 with Django 3.2.4

**Comment by 1am** [comment]
Eventually solution from #265 helped me with making it work.

**Comment by agualdron** [comment]
Try
`pip uninstall django-auditlog`

then
`pip install auditlog3`

as stated [here](https://stackoverflow.com/a/63914949/8629618)

It worked for me...

**Comment by Linkid** [comment]
This is the same issue of #265 ;). Thanks anyway to have reported it.
