### ISSUE TITLE
get_for_model() missing 1 required positional argument: 'model'

### ISSUE THREAD

**Issue by amin7mazaheri** [jazzband/django-auditlog#306]
when I am passing a model or instance for LogEntryManagement.get_for_model(), I face this error

**Comment by Linkid** [comment]
Hi ! Thanks for your report.
Which version of Django and django-auditlog are you using, please ?

**Comment by BosterJack** [comment]
![image](https://user-images.githubusercontent.com/56207603/174689070-b9ff314b-8679-48ec-ab03-7c95b8ecbd00.png)
I get the same thing

**Comment by WilliamOtieno** [comment]
You're supposed to use it this way...
```py
logs = auditlog.models.LogEntry.objects.get_for_model(YourModel)
```

**Comment by BosterJack** [comment]
Ok i will check it

**Comment by hramezani** [comment]
@amin7mazaheri Is it still a problem?

**Comment by WilliamOtieno** [comment]
> 

It shouldn't be. Refer to https://github.com/jazzband/django-auditlog/issues/306#issuecomment-1168482057

**Comment by hramezani** [comment]
Thanks @WilliamOtieno for letting me know!

**Comment by hramezani** [comment]
Thanks @WilliamOtieno for letting me know!
