### ISSUE TITLE
Dependency issue with dateutil==2.6.0

### ISSUE THREAD

**Issue by DerAndre** [jazzband/django-auditlog#314]
Hi folks,
first things first. Thank you, for providing the Django community with this amazing lib! Sadly I can't integrate it into a project due to a sub-dependency issue.
The requirements.txt doesn't specify any versions, and setup.py explicitly requires python-dateutil>=2.6.0.
When trying to install django-auditlog, I get:
  There are incompatible versions in the resolved dependencies:
    python-dateutil==2.6.0 (from django-auditlog==0.4.7)
    python-dateutil>=2.7.3 (from pandas==1.3.1)

Do you have any similar experience and/or a workaround? Would it be possible to upgrade the python-dateutil dependency?

Cheers

**Comment by skasidej** [comment]
Have you tried adding **auditlog3** package inside **requirements.txt** file, then re-run it again?

@DerAndre

**Comment by Kaffeetasse** [comment]
You could try `pip install -r requirements.txt --use-deprecated=legacy-resolver`

**Comment by Linkid** [comment]
Hi! This has been fixed in https://github.com/jazzband/django-auditlog/commit/33fa2490714954b189e24963e4586f86ce4f99c2. You can install django-auditlog 1.0a1 to have the fix, until the v1.0.0 is released: 

    pip install django-auditlog==1.0a1
