### ISSUE TITLE
No actor when using with Django Rest Framework

### ISSUE THREAD

**Issue by gsujaye** [jazzband/django-auditlog#318]
I am trying to use the auditlog in the Django Rest Framework project. All is working well except the part that when creating an object by API call, the user is saved as **system** and not proper request.user. Although it is working fine in the admin panel. Is there any fix or any way for this?

**Comment by adamwojt** [comment]
See here: https://github.com/jazzband/django-auditlog/issues/115

**Comment by Linkid** [comment]
Thanks for the report :).
I'm closing this issue as it is a duplicate.
