### ISSUE TITLE
KeyError in changes_display_dict Proxy Model

### ISSUE THREAD

**Issue by russell310** [jazzband/django-auditlog#320]
When looping over `changes_display_dict.items` creates KeyError
```
site-packages\auditlog\registry.py", line 104, in get_model_fields
    'include_fields': list(self._registry[model]['include_fields']),

Exception Type: KeyError at /account/user/logs/15/detail/
Exception Value: <class 'apps.contacts.models.Company'>
```

But `changes_dict.items` is ok

**Comment by hramezani** [comment]
@russell310 Sorry for the late response.
Could you please check the problem with `django-auditlog 2.2.0`?
Please let us know if the problem still exists.

**Comment by hramezani** [comment]
Feel free to open it again in case of the problem!
