### ISSUE TITLE
Release 0.4.9 / 1.0 ?

### ISSUE THREAD

**Issue by msde** [jazzband/django-auditlog#331]
I see a major 1.0 release coming, but in the meantime what I could really use is a version that is compatible with the rest of my requirements.txt, without having to pin to old versions of pip for `--use-deprecated=legacy-resolver`.

Is there any way the 0.4.7 branch could get 33fa2490714954b189e24963e4586f86ce4f99c2 cherry-picked into it, have the version bumped, and then released to pypi?

**Comment by Linkid** [comment]
Hi. I've checked, and there is a v0.4.8 tag already. I think the best thing to do is a new release, yes.

**Comment by PabloCastellano** [comment]
Please @jazzband release a new version :pray: of auditlog to pypi

**Comment by Linkid** [comment]
@hramezani : I think we can make a release (v1.0), now that Django 4.0 is supported. What do you think ?

**Comment by hramezani** [comment]
@Linkid sure we can make a new release but I am not sure about the `v1.0`.

**Comment by Linkid** [comment]
Is there another blocker for the v1.0 ?

**Comment by hramezani** [comment]
I am not sure as I am a lead for this package. it up to you to decide.

**Comment by PabloCastellano** [comment]
FWIW, I've been using this package for 2+ years and had zero troubles. Looks pretty stable to me and worthy of being v1.0. Open issues can be tackled later anyways

**Comment by hramezani** [comment]
@Linkid Yes, I can help :)

**Comment by Linkid** [comment]
@hramezani : nice :). Feel free to  [open a project lead issue](https://jazzband.co/roadies/issue) ;). I'll vote for you, for sure !

**Comment by Linkid** [comment]
@hramezani : if you need help to lead this project, I can make an issue to be co-leader with you. Tell me if you need it, or I will just be a helper in reviewing and triage (which is ok for me) :).

**Comment by hramezani** [comment]
@Linkid That would be great if you can help!

**Comment by hramezani** [comment]
@Linkid can we prepare a new release now?

**Comment by Linkid** [comment]
Yep, let's go :).

**Comment by Linkid** [comment]
The new release is available on PyPI, thanks to @hramezani. This issue can be closed :).
