### ISSUE TITLE
RemovedInDjango40Warning: ugettext deprecated in django 3 and removed in django 4

### ISSUE THREAD

**Issue by wearebasti** [jazzband/django-auditlog#334]
From first tests with Django 4.0 we seem to be "blocked" to upgrade Django versions by django-auditlog, as the pre-release version still uses at least in `auditlog/models.py` an import of `ugettext_lazy` which was deprecated in Django 3 and removed in Django 4.

This should be a pretty simple fix to "just' replace `ugettext_lazy` with `gettext_lazy`, hoping now other issues come up.

Versions:
- django 4.0
- django-auditlog 1.0a1.

**Comment by Linkid** [comment]
Done for the auditlog codebase. Next step, the `django-jsonfield` dependency.

**Comment by Linkid** [comment]
The PR #370 removes the dependency with the warning. So, I can close this issue.
