### ISSUE TITLE
Null value in column "log_version" violates not-null constraint

### ISSUE THREAD

**Issue by gatapov** [jazzband/django-auditlog#337]
I get an error when I try to create an object UserCourse

```
django.db.utils.IntegrityError: null value in column "log_version" violates not-null constraint
DETAIL:  Failing row contains (134407, 29450, 29450, UserCourse object (29450), 0, 2021-12-16 06:19:26.324922+00, null, 40, null, {"id": ["None", "29450"], "user": ["None", "test@mail.ru"], "co..., null, null).
```
in models:

```
from auditlog.registry import auditlog

class UserCourse(models.Model):
   ...

auditlog.register(UserCourse)
```

why can this happen?

**Comment by ahmadjubair33** [comment]
hi can i solve this issue?

**Comment by alieh-rymasheuski** [comment]
@gatapov, I don't think this issue is caused by django-auditlog as there is no such name as `log_version` in the project. The error message indicates that the `UserCourse` model has a `log_version` field with no default and it is not getting a value. Could you please provide the maintainers with a larger snippet or even a minimal failing example?

**Comment by alieh-rymasheuski** [comment]
> The error message indicates that the `UserCourse` model has a `log_version` field with no default and it is not getting a value.

I was wrong. This exception means that an object similar to `LogEntry` gets a null value in its `log_version`. I tried classifying the values listed in the exception message:

| field           | value                                                              |
|-----------------|--------------------------------------------------------------------|
| id              | 134407                                                             |
| object_pk       | 29450                                                              |
| object_id       | 29450                                                              |
| object_repr     | UserCourse object (29450)                                          |
| action          | 0                                                                  |
| timestamp       | 2021-12-16 06:19:26.324922+00                                      |
| actor_id        | null                                                               |
| content_type_id | 40                                                                 |
| remote_addr     | null                                                               |
| changes         | {"id": ["None", "29450"], "user": ["None", "test@mail.ru"], "co... |
| additional_data | null                                                               |
| ???             | null                                                               |

There is one extra field which is not present in the current version of `django-auditlog`. I don't think the upstream version of this package has ever had a `log_version` field. If this field is added in a fork, please direct this question to the corresponding fork or let's discuss it in a pull request.

Please reopen this issue if you think I'm wrong and this is indeed a bug of `django-auditlog`.
