### ISSUE TITLE
Logging access

### ISSUE THREAD

**Issue by simonkern** [jazzband/django-auditlog#345]
Unlike other packages like [django-simple-history](https://github.com/jazzband/django-simple-history), the package name django-auditlog implies (at least to me) that all audit-related information can be logged using this package. Unfortunately, this is currently definitely not the case.

As of now Auditlog only handles three of the four CRUD operations. Only the following types of operations are currently covered:
- CREATE
- UPDATE
- DELETE

However, from time to time it's also necessary to log access to objects (READ). At least in the EU, where the GDPR is widely applied, it is the rule rather than the exception that access to PII must be logged. These logs are then viewed and reviewed as part of data protection audits. Nearly all of the data protection officers with whom we work require such a mechanism.

This could be implemented, e.g., by means of a signal and a Mixin for usage in DetailViews etc. I have a unpolished but working version of this. Would this be of interest for the project and is there a chance to get this sort of addition merged?

Thanks!

**Comment by alieh-rymasheuski** [comment]
@simonkern, I allowed myself to edit the description of the issue to include your motivation you described in https://github.com/jazzband/django-auditlog/pull/436#issuecomment-1273694785. At least for me, that motivation was sufficient to change my opinion from "meh, who needs to log reads, that would bloat the log" to "this is a real-world requirement for real-world audits therefore it's valid". Please feel free to adjust the wording or even undo my edit completely if you will.

**Comment by simonkern** [comment]
@alieh-rymasheuski thank you very much. It is completely fine for me and I really appreciate this. I should have thought of this myself.

I hope I was able to convinve the others as well. What do you suggest how we should proceed here?

Whether this gets merged at some point or not, I think it makes sense to provide a mechanism for FBVs either way. What approach concerning FBVs would you and the other maintainers suggest / prefer?

**Comment by simonkern** [comment]
This has been merged in https://github.com/jazzband/django-auditlog/pull/436

**Comment by hramezani** [comment]
Fixed in #436
