### ISSUE TITLE
Build of 1.0.0 with option ignore-installed

### ISSUE THREAD

**Issue by juliushacker** [jazzband/django-auditlog#353]
Good evening everybody,

I tried to install django-auditlog on my development machine, which is behind a proxy actually.
To achieve that I got the source code from pypi.org and issued a pip install on it.
That resulted in an error as the installation routine tried to download setuptools, wheel and setuptool-scm with option ignore-installed.
It also wasn't possible to install it directly from central pip Repository with the corresponding --proxy parameter, with one difference:
For version 1.0.0, it resulted in the described error, but as a fallback, a "pip django-auditlog --proxy ..." was able to install Version 0.4.7 without any problems.

As I also won't have the possibility to tweak any proxy settings on my normal test and production machines, I would really appreciate it to have the ability to install the package without needed internet access and to have the possibility to get the package and all dependencies on my machines and then install it without internet access.

Do you see a possibility to either have an actual source package similar to 0.4.7 or to have prebuilt wheel packages?

Greets
Julius

**Comment by Linkid** [comment]
Hi ! Thanks for the report.

@hramezani : I don't know if you can, but could you upload the wheel for version 1.0.0 to PyPI, please ? It should have been generated with the dist file.

**Comment by hramezani** [comment]
@Linkid I am not sure but I will check it later.

**Comment by hramezani** [comment]
@juliushacker @Linkid the wheel is now available on PyPI.

**Comment by Linkid** [comment]
Ok, seems to work for me. What about you @juliushacker ?
