### ISSUE TITLE
An option to see differences or values before/after update in django admin

### ISSUE THREAD

**Issue by danaki** [jazzband/django-auditlog#371]

**Comment by hramezani** [comment]
Could you please explain more here?

**Comment by danaki** [comment]
Clicking on "History" button when editing model.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/1043805/176263338-ae7690dc-d372-40d7-88c5-c7bcaaf0d111.png">

Should have what changes to what.

**Comment by hramezani** [comment]
This is [Django history view](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.history_view) which is for Django itself.
Its not rendered by `django-auditlog`

**Comment by danaki** [comment]
Can it be replaced by a custom one?

**Comment by hramezani** [comment]
I am not sure what you have in your mind. but I think it is possible to use django-audit log and show the change history for the object there.

**Comment by alieh-rymasheuski** [comment]
You can make this a mixin class then.

**Comment by danaki** [comment]
Ok, thank you @alieh-rymasheuski, your solution helped me. Here's my modified chunk of your code:
```

class AuditlogForHistoryMixin:
    def history_view(self, request, object_id, extra_context=None):
        model = self.model
        obj = self.get_object(request, unquote(object_id))
        if obj is None:
            return self._get_obj_does_not_exist_redirect(request, model._meta, object_id)
        return HttpResponseRedirect(self.get_auditlog_url(obj))

    def get_auditlog_url(self, obj):
        ct = ContentType.objects.get(app_label=obj.__class__._meta.app_label, model=obj.__class__._meta.model_name)
        params = {"resource_type": ct.id, "object_id": getattr(obj, obj.__class__._meta.pk.name)}
        return "{}?{}".format(reverse("admin:auditlog_logentry_changelist"), urlencode(params))
```

**Comment by alieh-rymasheuski** [comment]
> `getattr(obj, obj.__class__._meta.pk.name)`

Isn't this equivalent to `obj.pk`?
