### ISSUE TITLE
![image](https://user-images.githubusercontent.com/56207603/174689070-b9ff314b-8679-48ec-ab03-7c95b8ecbd00.png)

### ISSUE THREAD

**Issue by BosterJack** [jazzband/django-auditlog#388]
![image](https://user-images.githubusercontent.com/56207603/174689070-b9ff314b-8679-48ec-ab03-7c95b8ecbd00.png)
I get the same thing

_Originally posted by @BosterJack in https://github.com/jazzband/django-auditlog/issues/306#issuecomment-1160955464_

**Comment by hramezani** [comment]
Hi, Thanks for reporting.
Which version of Django and django-auditlog are you using?

**Comment by hramezani** [comment]
Have you tried `LogEntry.objects.get_for_model(Personnel)` ?

**Comment by hramezani** [comment]
I close this one as it's a duplicate of https://github.com/jazzband/django-auditlog/issues/306
