### ISSUE TITLE
Please push version 2.1.0 to pypi

### ISSUE THREAD

**Issue by ewoudenberg-kasisto** [jazzband/django-auditlog#389]
The new m2m_fields feature is perfect for us. We'd love to be able to install this from pypi. -Thank you!

**Comment by RamitGC** [comment]
+1

**Comment by alcart** [comment]
+1

**Comment by hramezani** [comment]
I will prepare a new release soon.

**Comment by hramezani** [comment]
It's just released!
https://pypi.org/project/django-auditlog/2.1.0/
