### ISSUE TITLE
Deleted objects changes not displayed in admin

### ISSUE THREAD

**Issue by jvitors23** [jazzband/django-auditlog#393]
Why the changes are not displayed for deleted objects in the admin site? 

From the LogEntryAdminMixin:

![image](https://user-images.githubusercontent.com/52494917/176176282-1cc92fef-e67d-4cb2-b019-0696a75c78b8.png)

![image](https://user-images.githubusercontent.com/52494917/176176316-3473e0b2-c2d1-4b6c-a4e0-632fc760c7cc.png)

**Comment by hramezani** [comment]
If we have a model like:
```python
class MyModel(modelsModel):
    sku = models.CharField(max_length=20)
    version = models.CharField(max_length=5)
    product = models.CharField(max_length=50, verbose_name='Product Name')
    history = AuditlogHistoryField()
```
Then for a deleted object, 
`msg` is `4 changes: sku, id, version, product`

and `msg_short` is :
```
# | Field | From | To
-- | -- | -- | --
1 | id | 4 | None
2 | product | test product | None
3 | sku | test sku | None
4 | version | test version | None
```
Which is contain the last value of the object before delete.

So, I am not sure what was the reason that we return an empty string but I think we can remove this block.

@jvitors23 Would you like to prepare a patch with test to fix it?

**Comment by alieh-rymasheuski** [comment]
I suggest keeping `msg_short` empty (to keep the changelist visually cleaner) and only list the "changes" in `msg`.
