### ISSUE TITLE
Outdated dependency python-dateutil causing error

### ISSUE THREAD

**Issue by matthttam8411** [jazzband/django-auditlog#400]
By default django-auditlog appears to require python-dateutil  version >= 2.6.0.
On python 3.10 version 2.6.0 of dateutil has a bug that is actually breaking the changes_display_dict function.

Basically my tests started to fail:

```
        if not ignoretz:
>           if (isinstance(tzinfos, collections.Callable) or
                    tzinfos and res.tzname in tzinfos):
E                   AttributeError: module 'collections' has no attribute 'Callable'
```

<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AttributeError at /assignments/6/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">module 'collections' has no attribute 'Callable'</pre>

Request Method: | GET
-- | --
http://127.0.0.1:8000/assignments/6/
4.0.5
AttributeError
module 'collections' has no attribute 'Callable'
/home/bil/projects/python/django/inventory/venv/lib/python3.10/site-packages/dateutil/parser.py, line 587, in parse
/home/bil/projects/python/django/inventory/venv/bin/python
3.10.5
['/home/bil/projects/python/django/inventory/inventory',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/home/bil/projects/python/django/inventory/venv/lib/python3.10/site-packages']
Mon, 25 Jul 2022 21:50:28 -0500

</body>
</html>

The fix was to perform: `pip install python-dateutil==2.8.2`

python-dateutil doesn't yet support python 3.10 technically but the latest version is working for me.

I'd suggest changing your requirements to python-dateutil >= 2.8.2 to prevent this issue.

To recreate the issue:
`pip install python-dateutil==2.6.0`
```
from dateutil import parser
parser.parse('2022-07-26 02:07:44')
parser.parse('2022-07-26 02:07:44.729215')
```
Then repeate with `pip install python-dateutil >= 2.8.2

The error from django-auditlog occurs when a timestamp is used for a field on a model that is registered.

**Comment by alieh-rymasheuski** [comment]
@matthttam8411, thanks for the ticket and especially thanks for the code snippet which reproduces the issue.

As far as I can see, this issue was fixed in [python-dateutil 2.7.0](https://dateutil.readthedocs.io/en/stable/changelog.html#version-2-7-0), so we can set the requirement to `python-datutil>=2.7.0`. Do you see a compelling reason for django-auditlog to require an even newer version of `python-dateutil`?

**Comment by hramezani** [comment]
Seems we just use `python-dateutil` for handling `"DateTimeField", "DateField", "TimeField"`:

https://github.com/jazzband/django-auditlog/blob/ed3ce767627d88a8c84dc4f3192320690b42924f/auditlog/models.py#L385-L393

Maybe we can get rid of `python-dateutil` as a dependency but not sure if is it possible or not.

For now, I am ok with pinning the version to `>2.7.0` or `>2.8.2`.

**Comment by matthttam8411** [comment]
> python-dateutil

I can confirm that 2.7.0 passes all my tests for my app while 2.6.0 fails 4 tests out of 423.
I would recommend 2.8.2 only if some bugs have been corrected (like compatibility issues) etc. but I have nothing concrete to recommend it over 2.7.0.

I do second the idea of removing the dependency from python-dateutil but I don't know enough about django-auditlog to recommend a path for that. Maybe there is a django utility that can replicate what is needed... or maybe the model could store dates and times as their actual objects so you wouldn't need to convert them later.
