### ISSUE TITLE
`created` field returns datetime that is not timezone aware

### ISSUE THREAD

**Issue by HassanKadhem** [jazzband/django-auditlog#403]
In the log entry admin list page, the `created` field and because of using `strftime` returns a datetime that is not timezone aware. This creates confusion for applications that override the default time zone in the settings. I have already implemented a fix for this in my forked repo but I wanted to create an issue first to streamline rolling out the fix. I'm ready to submit the PR whenever the issue is approved, please assign me to this issue.

**Comment by alieh-rymasheuski** [comment]
This is one part of changes in my fork as well which I have wanted to push to upstream since times unknown. :)
