### ISSUE TITLE
[Enhancement] Use verbose name of field for display purpose

### ISSUE THREAD

**Issue by rptmat57** [jazzband/django-auditlog#426]
A possible enhancement for the **admin pages** and the **display str** functions would be to try to find the verbose name of the field and use it (and even capitalize it):

```python
try:
    field = logentry.content_type.model_class()._meta.get_field(field).verbose_name.capitalize()
except:
    pass
```

Just a thought.

**Comment by hramezani** [comment]
Thanks @rptmat57  for proposing this.
Could you please provide a picture of the change on the admin page?
Do you want to prepare a patch for your suggestion?

**Comment by hramezani** [comment]
Closed by https://github.com/jazzband/django-auditlog/commit/d74c118834ac9f4f5dd76fd443fe905491fcd976
