### ISSUE TITLE
Django 5 Error because of timezone.utc deprecation

### ISSUE THREAD

**Issue by andrewgy8** [jazzband/django-auditlog#427]
On installed version Django 4.1 and django-auditlog 2.1.1 we are witnessing:

>   /usr/local/lib/python3.9/site-packages/auditlog/diff.py:67: RemovedInDjango50Warning: The django.utils.timezone.utc alias is deprecated. Please update your code to use datetime.timezone.utc instead.
>     value = timezone.make_naive(value, timezone=timezone.utc)

Seems like we are using this deprecated feature in 2 places
- [here](https://github.com/jazzband/django-auditlog/blob/11dceb81b8eb39cfd8086b302d02f17f762cce2b/auditlog/diff.py#L67)
- [here](https://github.com/jazzband/django-auditlog/blob/777bd537e7d0a41a0f5baa562f2a3cbe20080bae/auditlog/models.py#L473)
- and [here](https://github.com/jazzband/django-auditlog/blob/777bd537e7d0a41a0f5baa562f2a3cbe20080bae/auditlog_tests/tests.py#L635) in the tests

Its simple to fix. Ive already done it in a couple projects I have. 

Seems like a great beginners friendly issue!

**Comment by hramezani** [comment]
Thanks @andrewgy8 for this issue.

Yes, it would be great!
