### ISSUE TITLE
Related Field got invalid lookup: username

### ISSUE THREAD

**Issue by dev-fairshares** [jazzband/django-auditlog#431]
- noticed while deleting logentires

**Comment by dev-fairshares** [comment]
![Screenshot from 2022-09-20 22-51-43](https://user-images.githubusercontent.com/105924251/191403554-0d39d4a0-7b61-4fa1-bbd1-e28a1db39c60.png)

**Comment by hramezani** [comment]
Could you please provide more information?

- django-auditlog version?
- Django version?

Also, we need a small example to reproduce the problem. it can be like a test or test project.

**Comment by alieh-rymasheuski** [comment]
@hramezani, I know the issue. @dev-fairshares likely uses a custom user model with no username field - I do so too. #210 added `actor__username` to search fields of the log entries admin, which fails whenever the user tries to search log entries (note the `?q=` in the URL on @dev-fairshares's screenshot). Let me port my fix to the upstream quickly.

**Comment by hramezani** [comment]
@alieh-rymasheuski Thanks for the investigation. might be the reason.
@dev-fairshares Can you confirm?

**Comment by dev-fairshares** [comment]
Yes @hramezani, I have replaced the username with the email field.  @alieh-rymasheuski  was able to reproduce it correctly.
