### ISSUE TITLE
Allowing ability to control which paths to track actor on in the middleware.

### ISSUE THREAD

**Issue by hashimamin** [jazzband/django-auditlog#437]
Hey all,

I have a use case where I want to track the user making the change on all URLs paths except a select few. 
EX:
- `/car` makes a change to the `Car` model and I want to track the user making the change
- `/car/door/1/get-info/material` makes a change to the `Car` model but I do not want to track the user in this case

Could this functionality be added to the AuditlogMiddleware via settings? Something like a list of paths to exclude from tracking the actor on?

**Comment by hramezani** [comment]
Hey,

If I understand you correctly, For some specific path, you want to have an audit record without a user. right?

As it's a very specific use case, I would  say you can have your own middleware inherited from [AuditlogMiddleware](https://github.com/jazzband/django-auditlog/blob/993cd847fb246ca30d66f1a77c6542bb5a2cafe8/auditlog/middleware.py#L6)

**Comment by hashimamin** [comment]
I appreciate the swift response! Sounds good, I'll go ahead and subclass the existing middleware. Thanks!
