### ISSUE TITLE
django-health-check with django-audit-log

### ISSUE THREAD

**Issue by rahulkp220** [jazzband/django-auditlog#441]
Hi,
I am trying to *ignore* django health check's `TestModel` from the `auditlog` app, but it doesn't seem to work.
Here is my setting,
```
# django auditlog
AUDITLOG_INCLUDE_ALL_MODELS = True
AUDITLOG_EXCLUDE_TRACKING_MODELS = (
    "health_check",
    "health_check.db.models.TestModel"
)
```
No matter what combination I add here, it always logs `create`, `update`, `delete` actions for the `TestModel` object.
Any insights on how I can ignore this model?

**Comment by hramezani** [comment]
@2ykwang Could you please take a look?

**Comment by 2ykwang** [comment]
@rahulkp220  Can you show the output when you run the code below in django shell? 

```shell
python manage.py shell (--settings=<your settings>)
```

```python
from django.apps import apps

apps.all_models["health_check"]
```

this code to check if `health_check` is the app name.

**Comment by rahulkp220** [comment]
Hi @2ykwang , your question led me to the solution :)

I started testing as you suggested,
```bash
./manage.py shell --settings myproject.settings

>> from django.apps import apps
>> apps.all_models["health_check"]
>> {}
```

However, I given I had the following in my `INSTALLED_APPS`
```bash
    "health_check",
    "health_check.db",
    "health_check.cache",
    "health_check.storage",
    "health_check.contrib.migrations",
    "health_check.contrib.redis",
```

But, upon further checking, I found that `django-health-check` was storing the app names as 
```bash
>> apps.all_models(
defaultdict(dict,
             ....
             'health_check': {},
             'db': {'testmodel': health_check.db.models.TestModel},
             'cache': {},
             'storage': {},
             'migrations': {},
             'redis': {},
             ....
)
```
So, I went ahead and added just `db` in my setting like this,
```bash
AUDITLOG_EXCLUDE_TRACKING_MODELS = (
    "db",
)

```

and it works now! 🎉 
Thank you!

**Comment by 2ykwang** [comment]
@rahulkp220 the app where `TestModel` is managed is `health_check.db` so you can try `db.TestModel`.
