### ISSUE TITLE
Config to skip auditlog during imports

### ISSUE THREAD

**Issue by robinharms** [jazzband/django-auditlog#443]
It would be great if it was possible to have a simple setting to disable logging for imports. (Essentially listening for raw=True)

Preferably a global setting. If this is something you world consider, I would be happy to make a patch.

**Comment by robinharms** [comment]
I've done the patch already, but can't seem to run the tests. :)
Sorry for asking dumb questions, executing runtests.py doesn't seem to work for me.

**Comment by hramezani** [comment]
Hi @robinharms,

How do you run your tests locally? have to tried to run the tests with `tox`?

**Comment by robinharms** [comment]
Actually no I hadn't, but when running the tests with tox I get the same error eventually:

  File "/Users/robin/PycharmProjects/django-auditlog/.tox/py39-django40/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 85, in connect
    raise TypeError("Signal receivers must be callable.")
TypeError: Signal receivers must be callable

**Comment by hramezani** [comment]
Did you get this error in fresh master as well?

**Comment by robinharms** [comment]
Yes, and I use the latest

**Comment by hramezani** [comment]
It might be related to your tox environment. Are you running your test in the console by running for example `tox -e py39-django40` command?

**Comment by robinharms** [comment]
Yeah I did.

Sure it has nothing to do with the changed signal handlers?

  File "/Users/robin/PycharmProjects/django-auditlog/.tox/py39-django40/lib/python3.9/site-packages/django/db/models/signals.py", line 27, in connect
    self._lazy_method(
  File "/Users/robin/PycharmProjects/django-auditlog/.tox/py39-django40/lib/python3.9/site-packages/django/db/models/signals.py", line 24, in _lazy_method
    return partial_method(sender)
  File "/Users/robin/PycharmProjects/django-auditlog/.tox/py39-django40/lib/python3.9/site-packages/django/dispatch/dispatcher.py", line 85, in connect
    raise TypeError("Signal receivers must be callable.")
TypeError: Signal receivers must be callable.

**Comment by robinharms** [comment]
Wait forget about this, It's another package wrapping this :)
Sorry to trouble you!

I'll recheck the tests and come back with a PR for the changes I made.

**Comment by hramezani** [comment]
Closed in https://github.com/jazzband/django-auditlog/commit/8fe776ae45964d20bf113d5bff9287398f89480a
