### ISSUE TITLE
Logging related model changes

### ISSUE THREAD

**Issue by moffire** [jazzband/django-auditlog#453]
Hi. I have 2 questions:
1) Can you please tell me if it is possible to log changes in the related model? Right now my code looks like this and changing value in field `field_1` in the model `A` not displayed in the database records. Am I missing something?
2) How can I pass `additional_data` for changes?

```
class A(models.Model):
    fk_on_other_model = models.ForeignKey('B', related_name='some_related_name', on_delete=models.CASCADE)
    field_1 = models.CharField()

class B(models.Model):
    ...

auditlog.register(B)
```

**Comment by hramezani** [comment]
Hi,

>Can you please tell me if it is possible to log changes in the related model? Right now my code looks like this and changing value in field field_1 in the model A not displayed in the database records. Am I missing something?

You need to [register your model](https://django-auditlog.readthedocs.io/en/latest/usage.html#automatically-logging-changes)

> How can I pass additional_data for changes?

Unfortunately, It's not documented. you can do it by adding a `get_additional_data` to your model. The method has to return a `dict`.
Take a look at this example: https://github.com/jazzband/django-auditlog/blob/2b0bc9efa2db94af2c5e130cce4e662cf3b2ad0e/auditlog_tests/models.py#L168-L178

**Comment by moffire** [comment]
@hramezani thank you!
