### ISSUE TITLE
Different actors when using a frontend proxy and different backend systems

### ISSUE THREAD

**Issue by dalvgui** [jazzband/django-auditlog#461]
Hi all!
I found an issue when using django-auditlog for multi-service environments. I think it may be interesting to identify the best way to support this. 

Usually the frontend acts as a proxy for other backends which could query the database and modify the data. As its  the middleware does not support this, and you cannot audit the real user who is requesting to modify the data. You'll only get the user which is used between services (for service connections). Here is an example to make it easier: 

![issue (1)](https://user-images.githubusercontent.com/36153922/204275955-283d8275-467b-4605-a0bb-355bac385e91.jpg)

As you can see in the image, I think it's common that between services they use their own credentials but never they 'll use the user credentials and it's the end user who should really be audited. 

**_first idea that surely is not the best_: _Maybe we should add one field to the LogEntry model (something like "author") to be able to pick it up from the request header to identify the end user ._

**Comment by dalvgui** [comment]
Thanks for answer!
This could work if the user data is shared between apps and user exists. 

As its my case (perhaps in many others) the authentication is not shared, I mean, the user doesn't exist in the backend service (only for the frontned app and auth app,  the rest of the services use tokens for authentication) then the foreign key of the model LogEntry would not allow call `set_actor(user)` with a user that doesn't exist.

Is there a way to allow this or should I extend the library for my case? Thanks!

**Comment by alieh-rymasheuski** [comment]
@dalvgui, I assume [`SomeModel.get_additional_data()`](https://github.com/jazzband/django-auditlog/blob/1674acae1926ff7268b3f3600264ffb150967076/auditlog/models.py#L55-L57) method isn't helping as well because the extra data you want to capture is an attribute of the API request, not an attribute of a model being updated?

**Comment by dalvgui** [comment]
Great, I didn't see the field `LogEntry.additional_data`, then I can fix my problem. If it helps others, for adding extra information,  I'm using a extra `middleware.py` and `context.py`  (inspired of these [middleware.py](https://github.com/jazzband/django-auditlog/blob/master/auditlog/middleware.py) & [context.py](https://github.com/jazzband/django-auditlog/blob/master/auditlog/context.py)). Finally with them, I add my own data to `LogEntry.additional_data` field.

**Comment by hramezani** [comment]
Yes, the `LogEntry.additional_data` is not documented. we have an issue documenting it https://github.com/jazzband/django-auditlog/issues/454.
