### ISSUE TITLE
TypeError object of type 'NoneType' has no len() when changes are empty

### ISSUE THREAD

**Issue by rptmat57** [jazzband/django-auditlog#477]
The admin logentry list throws a `TypeError object of type 'NoneType' has no len()` when json.loads() return None
I think this comes from https://github.com/jazzband/django-auditlog/blob/703e3e4ba6ba7127cbd6a1bbf2597504089ba78c/auditlog/mixins.py#L58
where:
```python
changes = json.loads(obj.changes)
s = "" if len(changes) == 1 else "s"
        fields = ", ".join(changes.keys())
```

this is related (if not the exact same thing) to #471 

I think a fix would be as simple as replacing `json.loads()` by `obj.changes_dict`

**Comment by hramezani** [comment]
Thanks @rptmat57 for reporting.
Could you please prepare a patch with a test?
