### ISSUE TITLE
Convert `AUDITLOG_EXCLUDE_TRACKING_MODELS` to tuple before concatenate

### ISSUE THREAD

**Issue by aivarsk** [jazzband/django-auditlog#486]
env\lib\site-packages\auditlog\registry.py", line 250, in _get_exclude_models
    for app_model in exclude_tracking_models + self.DEFAULT_EXCLUDE_MODELS
TypeError: can only concatenate list (not "tuple") to list

**Comment by hramezani** [comment]
Could you please share your configurations? it might be a wrong configuration problem.
what is the value of `DEFAULT_EXCLUDE_MODELS`?

**Comment by aivarsk** [comment]
I thought it complains about this one https://github.com/jazzband/django-auditlog/blob/master/auditlog/registry.py#L41

But yeah, AUDITLOG_EXCLUDE_TRACKING_MODELS is a list in my settings. Making it a tuple solves the issue.

**Comment by hramezani** [comment]
We can improve it [here](https://github.com/jazzband/django-auditlog/blob/dff0dd0fa509b39211cf0800f6aacbe88d94a2cd/auditlog/registry.py#L250) and convert it to a tuple before concatenate.

@aivarsk Would you like to work on this?

**Comment by aivarsk** [comment]
yeah, I can do that later today
