### ISSUE TITLE
Logging Related Models Fields Changes 

### ISSUE THREAD

**Issue by MuhammadHamed** [jazzband/django-auditlog#494]
If I have a model that has a foreign key or one to one or one to many relations, is there a way to get the fields changed in these related models in the log of the model having these relations?
Because as of now if I am correct, the log of the model only shows the ID to these related models and so if I changed something in one of the fields of these related models, the log of my model will not show me this change (as the ID to the related model instance is the same)

**Comment by hramezani** [comment]
If I got you right. you want to have the parent model changes log in the child's model. Then you may need to register some receiver for change signal of parent model

**Comment by MuhammadHamed** [comment]
@hramezani  Thanks I ended up using the following strategy:

- registering the child models but disconnecting its signals using the function _disconnect_signals 
- comparing the child model instances before saving the parent instance
- creating a manual log entry with the changes

I hope this can help someone facing a similar situation 

- the model_instance_diff function for comparing the differences between the child models before saving the parent model and
