### ISSUE TITLE
Extend/customize LogEntry model

### ISSUE THREAD

**Issue by kershner** [jazzband/django-auditlog#501]
Hi all - this is more of a question than an issue.

I would like to make use of the audit log, but I want the ability to customize the `LogEntry` model.  For instance, I'd like to have an additional field that is populated with custom data on each admin save.

So for this functionality I'd need: the ability to customize the `LogEntry` model (perhaps through a proxy?), and also the ability to hook into the methods that create the `LogEntry` when a user clicks "save" from the admin.

I see in the documentation that there are `pre_log` and `post_log` signals coming in v 3.0:
https://django-auditlog.readthedocs.io/en/latest/internals.html#auditlog.signals.post_log

These signals would be a potential solution, creating/populating my proxy model after the initial `LogEntry` is saved.  But obviously this code is not available yet!

What do you all think about this idea, is there a better way to accomplish it rather than just waiting for 3.0 and the new signals?  Let me know if more info is required.

**Comment by hramezani** [comment]
Hi, 

You can install the main branch of `django-auditlog` just for testing. Then you will understand whether the signal is enough or not.
Also, You can add an `additional_data` method to your model to provide additional data for each log entry. it is unfortunately not documented yet. but we have [an issue](https://github.com/jazzband/django-auditlog/issues/454) for that.

The `V3` release time is not defined yet. we are working on it and it has some breaking changes.
