### ISSUE TITLE
M2M `changes_dict` returns an `str`

### ISSUE THREAD

**Issue by josefdlange** [jazzband/django-auditlog#513]
I'm not 100% sure exactly how this is happening, but I believe M2M changes are being logged such that when `changes_dict` returns the result of  `json.loads(self.changes)`, it returns the JSON string. Looking at the database values, I can confirm that the value of the `changes` column, at rest, is a double-JSON-dumps'd version of the data.

```
"{\"managers\": {\"type\": \"m2m\", \"operation\": \"add\", \"objects\": [\"<redacted>\"]}}"
```

I think the new JSONField `changes` field is incompatible with the existing behavior of `json.dumps`-ing M2M data into `changes`.

For now I can just double-unwrap in this case, but if you agree this is a bug, I'm happy to post a PR for it in due time.

**Comment by josefdlange** [comment]
Well, disregard part of my investigation. There's no `JSON.loads`, I was mixing code versions I was reading. That said, the JSONField _is_ storing a _string of a JSON string_, such that `JSONField`'s own deserializing code returns just a `str`. Gonna throw together a PR with some tests.

**Comment by hramezani** [comment]
Fixed in https://github.com/jazzband/django-auditlog/commit/98fe8d4173868bdde7961d5d670183595dcae3bb

**Comment by hramezani** [comment]
It's not part of `2.3.0`.
It's part of next major release `v3`
