### ISSUE TITLE
Actor doesn't save when using raw data or json authentication

### ISSUE THREAD

**Issue by RAYLIEGH845163** [jazzband/django-auditlog#532]
Actor saves fine when I'm working with form-data
But when I use raw data to save/create/update actor is set to null.
I can't find the solution to this issue

**Comment by RAYLIEGH845163** [comment]
![image](https://github.com/jazzband/django-auditlog/assets/59432324/265e21d7-37a6-4208-95d9-9a20402ed4c0)

When I create a ward instance from the django rest framework actor is saved without any issue.
![image](https://github.com/jazzband/django-auditlog/assets/59432324/184568e1-3746-4ae8-be9a-92d3d67a1306)

But when I create ward from postman. The actor is not set.
![image](https://github.com/jazzband/django-auditlog/assets/59432324/a47221c1-9155-48fb-bd7e-d26a61805bbb)

![image](https://github.com/jazzband/django-auditlog/assets/59432324/0fda62d2-5dda-4314-becd-22d291ec5d4f)

I have set the middleware
![image](https://github.com/jazzband/django-auditlog/assets/59432324/8d6bad14-17e8-4c7c-b113-35c6cbd02504)

and this is the settings configuration
![image](https://github.com/jazzband/django-auditlog/assets/59432324/53be6142-ab0a-4647-98b4-80b4ac961d51)

**Comment by RAYLIEGH845163** [comment]
![image](https://github.com/jazzband/django-auditlog/assets/59432324/6403ff4b-3a8c-49a1-a21e-878a4b6cede8)

I have used inherit from auth parent in authorization header
even if i usee Oauth 2.0
or bearer roken as the authorization header it doesn't work

**Comment by RAYLIEGH845163** [comment]
It's ok if this doesn't work.

I would want to learn to override the LogEntry model or add some field to it
and use the CustomLogentry model instead.

I did the following but it doesn't work

from django.db import models
from auditlog.models import LogEntry

class CustomLogEntry(LogEntry):
    # Add any additional fields or modifications to the LogEntry model here
    # For example, you can add a custom field to track the source of the log entry.

    source = models.CharField(max_length=100, blank=True, null=True)

python manage.py makemigrations
python manage.py migrate

and added this to the settings
LOG_ENTRY_MODEL = 'auditlog_custom.CustomLogEntry'

**Comment by hramezani** [comment]
> It's ok if this doesn't work.

it is not clear to me what is the problem or even does `auditlog` have a problem. we need to have more information about the request object that comes to django and then auditlog. 

> I would want to learn to override the LogEntry model or add some field to it
and use the CustomLogentry model instead.

I think currently it is not possible to do it. you can have additional data in the model (this feature is not documented yet). please take a look at this issue https://github.com/jazzband/django-auditlog/issues/501


Where did you find `LOG_ENTRY_MODEL` setting?

**Comment by RAYLIEGH845163** [comment]
I got it from chatgpt
