### ISSUE TITLE
v2.3.0 doesn't seem to support Correlation ID

### ISSUE THREAD

**Issue by KungFuLucky7** [jazzband/django-auditlog#533]
v2.3.0 doesn't seem to support Correlation ID despite the documentation says the current version supports it:
https://django-auditlog.readthedocs.io/en/latest/usage.html#correlation-id
> New in version 2.2.0.
> AUDITLOG_CID_HEADER
> New in version 3.0.0.
> AUDITLOG_CID_GETTER

How and when can I use this Correlation ID feature for `django-auditlog`? Thanks!

**Comment by hramezani** [comment]
It's on main and will be released on next major version `v3`.
