### ISSUE TITLE
How to log operations on Queryset (update, bulk_create, bulk_update)?

### ISSUE THREAD

**Issue by VinshnuVd** [jazzband/django-auditlog#537]
I have tried to do the operations on a Queryset object and these changes are not been logged in AuditLog tables
```py
data = MyModel.objects.filter(field1='value')
data.update(filed2='new value')
```

In addition to the above operations I was not able to see the entries in auditlog table in bulk_create and bulk_update operations as well

Can anyone suggest how I can track change logs in above operations?

**Comment by hramezani** [comment]
The following issues are related. Please take a look

https://github.com/jazzband/django-auditlog/issues/515
https://github.com/jazzband/django-auditlog/issues/203

**Comment by VinshnuVd** [comment]
Thanks for the reply
