### ISSUE TITLE
[new user] Version 3.0.0 creating a migration file?

### ISSUE THREAD

**Issue by sdshone** [jazzband/django-auditlog#570]
We've newly started using auditlog in our project and started directly with the 3.0.0 version.
Based on [this](https://github.com/jazzband/django-auditlog/issues/503) issue, we did not add the said flags as it says it can be ignored by new users

 Our project creates a migration file for verbose name change to `changes_text` field as the [models.py](https://github.com/jazzband/django-auditlog/blob/master/auditlog/models.py#L342) shows the verbose name
as "change message" but the [migrations](https://github.com/jazzband/django-auditlog/blob/master/auditlog/migrations/0015_alter_logentry_changes.py#L27) file has the verbose name as "text change message".

This looks like a mixup, I did try adding the flags to our project after which we stop seeing the new migration file but that does not feel like the right solution. From a new users perspective the models.py and the migrations file do not look like they are in sync.

**Comment by hramezani** [comment]
@aqeelat Could you please take a look at this?

**Comment by hramezani** [comment]
Thanks @sdshone for reporting this. There is a PR to fix the problem.

We will prepare the new beta release soon

**Comment by hramezani** [comment]
New beta is available https://pypi.org/project/django-auditlog/3.0b2/
