### ISSUE TITLE
why not just use django's JsonField for LogEntry.changes??

### ISSUE THREAD

**Issue by engAmirEng** [jazzband/django-auditlog#575]
I'm trying to filter changes based on what changes applied to the entity and I wonder why `changes` is still TextField??
is you just convert it to JsonField i could easily query it
```[tasklist]
### Tasks
```

**Comment by hramezani** [comment]
[`changes` is `JsonField` on the master branch](https://github.com/jazzband/django-auditlog/blob/6b7f4a7ed4472ed40dc22a00884911c32973e318/auditlog/models.py#L343). we are preparing `django-auditlog` for version 3 and it's on beta right know.
