### ISSUE TITLE
post_save / post_log question

### ISSUE THREAD

**Issue by stahlnow** [jazzband/django-auditlog#576]
I have questions about `post_save` and `post_log`. In my requirement I want to take action on the object at the time it is being logged.

My first attempt was using `post_save`. Here's the issue: when I receive `post_save` for the `LogEntry`, at this moment, the object that is being logged is not saved yet. Is it possible to have the `post_save` of LogEntry _after_ the object was saved?

Second attempt was using the `post_log` signal instead. Here the object being logged is saved already, but another requirement is missing: The `post_log` signal does not include the actor. Is it possible to include it?

**Comment by hramezani** [comment]
@aqeelat do you have any idea here?
