### ISSUE TITLE
foreign key field changes are not reflecting in audit log

### ISSUE THREAD

**Issue by Karpuraraj** [jazzband/django-auditlog#583]
I have model "Order" which has foreign key "company". I have changed this company from my site, but the audit log not capturing it. here is how i am doing it. I am using update() method to update the data for filtered objects(e.g. Order.objects.filter(id__in=[1,2,3])).update(company=1). Any idea why its not working or how to make it right pls? Thanks
auditlog.register(
    Order,
    include_fields=["company"]
    serialize_data=True,
)

**Comment by hramezani** [comment]
Take a look at https://github.com/jazzband/django-auditlog/issues/515
