### ISSUE TITLE
Dynamic cross-instance register/unregister

### ISSUE THREAD

**Issue by kiblik** [jazzband/django-auditlog#586]
Hello,

we are developing and running a Django app
- which is horizontally scalable on main Django instances as well as on Celery instances
- with a focus on allowing a user to configure as many parameters from inside of the application (without the necessity to change environment variables and/or restart instances)

In this setup, we would like to get users the ability to enable and disable audit-logging. 

*Question: Is this possible?* I do not think so. But I will be more than happy if somebody will provide instructions on how to achieve our goals.

The reason why it is not possible in my opinion: To enable/disable audit-logging for each model, it is necessary to call `auditlog.register(Model_Name)`/`auditlog.unregister(Model_Name)` and this call has only local effect. So change will happen only on the instance which processes the user's request and it won't be propagated to other Django and Celery instances.

Because of this, if we would like to stay scalable, we are forced to change the setting via environment variables before each instance is started.

Am I right or is there some way, to dynamically enable/disable audit-logging?

**Comment by hramezani** [comment]
Please check [my comment](https://github.com/jazzband/django-auditlog/issues/589#issuecomment-1822749172) on a related issue. probably it would useful.

**Comment by kiblik** [comment]
> Please check [my comment](https://github.com/jazzband/django-auditlog/issues/589#issuecomment-1822749172) on a related issue. probably it would be useful.

Thanks @hramezani. Yes, your proposal might be the way for our enviroment. Let's wait for implementation, review and release.

**Comment by hramezani** [comment]
@kiblik We merged https://github.com/jazzband/django-auditlog/pull/590 and it will be available in the next beta release for testing.

**Comment by kiblik** [comment]
@hramezani, looks nice, thank you.
I might be able to run a local test, but I cannot add to our project until your change is not part of an official (non-beta) release.
