### ISSUE TITLE
Conditionally disable logging

### ISSUE THREAD

**Issue by errrken** [jazzband/django-auditlog#589]
Lets say I have an application where a user belongs to a company where audit logging is optional. 

Ideally I would like to attach a callback per model, that is run pre-save, and this callback should get the object to be saved and return a boolean if logging should be enabled / disabled.

Is there anyway I can do this today, by overriding some functionality? 

Thanks

#586 Looks like this is sort of a similar question

**Comment by hramezani** [comment]
Right now it is not possible to do it or probably you need to change a lot of things.

- Defining a method on the model to enable/disable logging per instance.
- Using `pre_log` signal result to prevent logging

PR welcome to add this feature

**Comment by errrken** [comment]
@hramezani Yeah. Would it make sense that if the pre_log signal returns False, then no logging would be made?

**Comment by hramezani** [comment]
Yeah, that would be an option as well. What do you think @aqeelat
