### ISSUE TITLE
LogUpdate entries can be created even when the object is not saved

### ISSUE THREAD

**Issue by hackoder** [jazzband/django-auditlog#593]
Looks like [log_update is connected to a pre_save signal](https://github.com/jazzband/django-auditlog/blob/master/auditlog/registry.py#L61), which can result in log entries being created even when the object does not get saved. Wouldn't post_save be more accurate?

**Comment by 2ykwang** [comment]
https://github.com/jazzband/django-auditlog/blob/master/auditlog/receivers.py#L56


by the condition branching, the case 'log entry could be created even if not saved', will not occur
