### ISSUE TITLE
Roadmap or timeline form v3.0.0 release?

### ISSUE THREAD

**Issue by neilmb** [jazzband/django-auditlog#600]
We (https://github.com/cisagov/manage.get.gov/) are excited for the JSON `changes` field coming in version 3.0.0 but I didn't see a schedule or a roadmap on when the code will move from v3.0.0b4 to the full 3.0.0 release on PyPI.

Is there a timeline for the 3.0.0 release? Or a roadmap of what needs to happen before that release?

Thanks so much for this fine module.

**Comment by hramezani** [comment]
We are very close to release 3.0.0 . Hopefully, the `v3.0.0b4` is the last beta release.

It would be great to you test the `v3.0.0b4` in your setup(if you already are using django-auditlog) and try to [migrare your existing data](https://django-auditlog.readthedocs.io/en/latest/upgrade.html) and let us know.

**Comment by hramezani** [comment]
@alphatownsman It would be great to test the latest beta.

**Comment by hramezani** [comment]
@alphatownsman hopefully next week

**Comment by hramezani** [comment]
django-auditlog 3.0.0 has been released!
