### ISSUE TITLE
Serialize __proxy__ objects before logging

### ISSUE THREAD

**Issue by Theoabw** [jazzband/django-auditlog#606]
Currently it's a pain to try to get changes Django's lazy translation object easily logged. Could implement some functionality to automatically detect __proxy__ object in models and transform them into strings before logging.

Context:

[https://www.perplexity.ai/search/How-do-I-DcNB.8jtQOu5Mm6lfO6Yfw?s=c#0dc341fb-c8ed-40eb-b932-6ea57cee987f](https://www.perplexity.ai/search/How-do-I-DcNB.8jtQOu5Mm6lfO6Yfw?s=c#0dc341fb-c8ed-40eb-b932-6ea57cee987f)

**Comment by hramezani** [comment]
Fixed in https://github.com/jazzband/django-auditlog/commit/a93d9ef6650132566185b66ad7f69a52b7df40ef
