### ISSUE TITLE
Boolean Field's update is not logged in auditlog_LogEntry model.

### ISSUE THREAD

**Issue by Aliza05** [jazzband/django-auditlog#612]
AUDITLOG_DISABLE_ON_RAW_SAVE = True
AUDITLOG_INCLUDE_TRACKING_MODELS = (
    'dept_admin.SIR',
    'dept_admin.SystemConfiguration',
    'dept_admin.PartialComment',
    'dept_admin.SIRFactors',
    'dept_admin.ScoringLevels',
    'dept_admin.FeatureFlag',
    'dept_admin.AdminEmailRecipients',
    'dept_admin.DeactivateEvaluationReason',
    {
        'model': 'auth.User',
        'exclude_fields': ['last_login'],
    },
    'evaluation_scheduler.ScheduleVariable',
    'evaluation_scheduler.ScheduledEvaluation',
    'evaluation_scheduler.Reminder',
    'evaluations.EvaluationSubmission',
    'evaluations.EvaluationHierarchy',
    'evaluations.EmployeeSignature',
    'fist_bumps.FistBump',
    'fist_bumps.SaluteFactors',
    'notification.SendGridTemplate',
    'notification.TemplateDynamicData',
    'supervisor.Notes',
    'supervisor.NoteBook',
    'webhooks.SendgridWebhookLog',
    'webhooks.LoggedNotifications',
    'wform.Employee',
    'wform.AddressDetail',
    'wform.Category',
    'wform.Question',
    'wform.QuestionOption',
    'wform.FireForm',
)
This is how I configured AuditLog in my project's settings.py file but for all the models, whenever I update a field from UI which is of type boolean it doesn't log it.

**Comment by Aliza05** [comment]
'auditlog.middleware.AuditlogMiddleware',
added this middelware too, and
'auditlog',
added this in the installed apps

**Comment by hramezani** [comment]
Not enough information. django-auditlog logs changes for boolean.

Feel free to open the issue again if you have problem.
