### ISSUE TITLE
Have custom AuditLogModelRegistry

### ISSUE THREAD

**Issue by hoangquochung1110** [jazzband/django-auditlog#617]
I'd like to have sth like this
```
from auditlog.registry import AuditlogModelRegistry

create_only_auditlog = AuditlogModelRegistry(
    create=True,
    update=False,
    delete=False,
    access=False,
    custom={
        post_save=my_signal_handler
    }
)

create_only_auditlog.register(MyModel)
```

But the problem is that we can not use this `create_only_auditlog`

because [model_instance_diff](https://github.com/jazzband/django-auditlog/blob/master/auditlog/diff.py#L108) would throw `KeyError` as it always get the default `auditlog`

Can we have new settings attribute to declare our custom auditlogs ?

**Comment by hramezani** [comment]
Thanks @hoangquochung1110 for this feature. having a new settings attributes seems a good idea

**Comment by hoangquochung1110** [comment]
Hi @hramezani Can I open a PR for it ?

My plan is to have a new settings attr let's say `AUDITLOG_REGISTRY`

We also may have `AuditlogRegistry` which acts as "facilitator" which help keep track of auditlogs with a variety of different configurations.

And the last thing. we may modify [model_instance_diff](https://github.com/jazzband/django-auditlog/blob/master/auditlog/diff.py#L108C5-L108C24) to get rid of its dependence on the default `auditlog`

**Comment by hramezani** [comment]
@hoangquochung1110 Yes, go for it.
