### ISSUE TITLE
Is it possible to change the date/time format when using changes_display_dict?

### ISSUE THREAD

**Issue by Tom5421** [jazzband/django-auditlog#636]
Hi, 

When using the changes_display_dict functionality, is it possible to change the date/time format? 

Not all my changes fields are datetime objects so I can't just apply the normal date filter inside the template.

I would like to change the date/time format for all my models, so some kind of global setting would be perfect.

**Comment by hramezani** [comment]
`django-auditlog` uses `formats.localize()` to convert datetime to string.
Have you tried changing the [DATETIME_FORMAT](https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-DATETIME_FORMAT) settings?

**Comment by Tom5421** [comment]
Thanks for the reply, I've tried using these options in my settings but it doesn't change the output of changes_display_dict

DATETIME_FORMAT = "j/m/Y, H:i"
DATE_FORMAT = "j/m/Y"

**Comment by hramezani** [comment]
Take a look at [django custom format files doc](https://docs.djangoproject.com/en/5.0/topics/i18n/formatting/#creating-custom-format-files).

You need to set the `FORMAT_MODULE_PATH` settings and create the custom format directory based on the doc

**Comment by Tom5421** [comment]
That has got it working, thank you.
