### ISSUE TITLE
Is it possible to log accesses to an object while using function based views?

### ISSUE THREAD

**Issue by Tom5421** [jazzband/django-auditlog#658]
Hi, is it possible to log accesses to an object while using function based views?

If this is possible, could we update the documentation to show how it can be done?

Thanks
Tom

**Comment by mohsiniscoding** [comment]
I didn't test it, but I think you can do:

```python
## views.py
from auditlog.signals import accessed

def profile_view(request, pk):
    user = User.objects.get(pk=pk)
    ## log access
    accessed.send(user.__class__, instance=user)
    # your custom logic as usual
    return render(request, 'view_profile.html', context={'user':user})
    ...
```

**Comment by Tom5421** [comment]
That worked, thank you! 

It would be great if this was added to the documentation :)

**Comment by hramezani** [comment]
@mohsiniscoding @Tom5421 Feel free to make a PR and add it to the doc

**Comment by mohsiniscoding** [comment]
@hramezani here is the PR ready to merge: https://github.com/jazzband/django-auditlog/pull/662

**Comment by hramezani** [comment]
Thanks @mohsiniscoding
