### ISSUE TITLE
Why does audit log creates duplicate permissions for single LogEntry model?

### ISSUE THREAD

**Issue by mohsiniscoding** [jazzband/django-auditlog#660]
I've added the django auditlog to my project. I've different user groups with `is_staff=True`. I want to allow some users to only view `LogEntries` table and detail page (view_logentry permission). when I add permission `view_logentry` to my `Group` it shows this error:
```
CommandError: Unable to load data: get() returned more than one Permission -- it returned 2!
```

It's because there are multiple permission for the same `LogEntry` model, check the image below:
![image](https://github.com/user-attachments/assets/312ac5f3-f722-40a7-8f2d-13a965e8b370)

To properly add the permissions I'm using this approach:
```python
for permission in Permission.objects.filter(codename='view_logentry'):
    if permission.natural_key()[1] == 'auditlog':
        group.permissions.add(permission)
```

But I still want to know if there is an issue with my implementation or this result is expected duplicate permission codename)
Thanks!

**Comment by hramezani** [comment]
The`Administration | log entry| ...` is for [django admin app LogEntry model](https://github.com/django/django/blob/7e00fee3bd3b780667f072325bdb69f29144c553/django/contrib/admin/models.py#L104) which is a different model than `auditlog.LogEntry`. I added both view permission from both app and it works.
