### ISSUE TITLE
Add new option to truncate log entries when calling flush command

### ISSUE THREAD

**Issue by BinDruid** [jazzband/django-auditlog#680]
I wonder if it is a good idea to truncate (and possibly restart the identity) for the log entry table instead of deleting records. This can be particularly useful in a scenario where the log entry table contains many records.

Obviously, Django ORM has no truncate method, and depending on the database vendor, a raw SQL query should be executed using a connection cursor.

**Comment by hramezani** [comment]
Flush command accepts a `-before-date` as an optional argument. But truncate delete all the record and doesn't have `where`.

**Comment by BinDruid** [comment]
Thanks for the clarification. I have updated the original issue title for clarity.

What I suggest is to introduce a new command called `auditlogtruncate` while keeping `auditlogflush`.
New command truncates the log entry table if it has grown too large and if user confirms it.

**Comment by hramezani** [comment]
The other option is to update the flush command and add a new argument like `-truncate`. then we need to:
- Check whether the backend db supports it
- Raise an error if the user passed `-before-data` and `-truncate` together.

By the way, I am also open to your suggestions.

**Comment by BinDruid** [comment]
> add a new argument like -truncate

I also lean towards using a new argument rather than introducing a new command.

> Raise an error if the user passed -before-data and -truncate together.

You are correct about the combination of these options. They should be mutually exclusive, and user cannot pass both of them.

If you are okay with that, I can prepare a PR to implement truncate for databases that support it and raise an appropriate error for databases that do not.

**Comment by hramezani** [comment]
> > add a new argument like -truncate
> 
> I also lean towards using a new argument rather than introducing a new command.
> 
> > Raise an error if the user passed -before-data and -truncate together.
> 
> You are correct about the combination of these options. They should be mutually exclusive, and user cannot pass both of them.
> 
> If you are okay with that, I can prepare a PR to implement truncate for databases that support it and raise an appropriate error for databases that do not.

That would be great. Go for it!

**Comment by BinDruid** [comment]
@hramezani
I have created a PR.
Testing this feature is somehow tricky and I'm not sure how should I approach it.
For now I have just tested against `postgresql` database backend. Testing the execution of `truncate` statement required using django class `TransactionTestCase`.
Any feedback would be appricated.
